//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Category { get; set; }
        public int BloodGroupId { get; set; }
        public string Relation { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> Age { get; set; }
        public string CardNo { get; set; }
        public string ImagePath { get; set; }
        public int MemberRegisterId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MemberRegister MemberRegister { get; set; }
        public virtual MasterBloodGroup MasterBloodGroup { get; set; }
    }
}
