//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipBenefit
    {
        public int Id { get; set; }
        public string MembershipName { get; set; }
        public string MemberPrefixCode { get; set; }
        public int MembershipCategoryId { get; set; }
        public int DurationId { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> MaxAdult { get; set; }
        public Nullable<decimal> MaxChild { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MembershipCategory MembershipCategory { get; set; }
        public virtual MembershipDuration MembershipDuration { get; set; }
    }
}
